# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\"\x06\n\x04Void\"&\n\x06\x43\x61mera\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08isActive\x18\x02 \x01(\x08\")\n\x10GetCamerasResult\x12\x15\n\x04list\x18\x01 \x03(\x0b\x32\x07.Camera\":\n\x1aSetCameraActivenessRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08isActive\x18\x02 \x01(\x08\"&\n\x18SubscribeOnCameraRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1a\n\nVideoChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\x12GetRecordsResponse\x12\x0f\n\x07records\x18\x01 \x03(\t\"&\n\x18SubscribeOnRecordRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x13RemoveRecordRequest\x12\n\n\x02id\x18\x01 \x01(\t\"F\n\x0c\x41\x63tionReport\x12\x14\n\x0cisSuccessful\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2\xd9\x02\n\x03\x41PI\x12(\n\nGetCameras\x12\x05.Void\x1a\x11.GetCamerasResult\"\x00\x12\x43\n\x13SetCameraActiveness\x12\x1b.SetCameraActivenessRequest\x1a\r.ActionReport\"\x00\x12?\n\x11SubscribeOnCamera\x12\x19.SubscribeOnCameraRequest\x1a\x0b.VideoChunk\"\x00\x30\x01\x12*\n\nGetRecords\x12\x05.Void\x1a\x13.GetRecordsResponse\"\x00\x12?\n\x11SubscribeOnRecord\x12\x19.SubscribeOnRecordRequest\x1a\x0b.VideoChunk\"\x00\x30\x01\x12\x35\n\x0cRemoveRecord\x12\x14.RemoveRecordRequest\x1a\r.ActionReport\"\x00\x62\x06proto3'
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=19,
)


_CAMERA = _descriptor.Descriptor(
  name='Camera',
  full_name='Camera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Camera.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='Camera.isActive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=59,
)


_GETCAMERASRESULT = _descriptor.Descriptor(
  name='GetCamerasResult',
  full_name='GetCamerasResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='GetCamerasResult.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=102,
)


_SETCAMERAACTIVENESSREQUEST = _descriptor.Descriptor(
  name='SetCameraActivenessRequest',
  full_name='SetCameraActivenessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SetCameraActivenessRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='SetCameraActivenessRequest.isActive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=162,
)


_SUBSCRIBEONCAMERAREQUEST = _descriptor.Descriptor(
  name='SubscribeOnCameraRequest',
  full_name='SubscribeOnCameraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SubscribeOnCameraRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=202,
)


_VIDEOCHUNK = _descriptor.Descriptor(
  name='VideoChunk',
  full_name='VideoChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VideoChunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=230,
)


_GETRECORDSRESPONSE = _descriptor.Descriptor(
  name='GetRecordsResponse',
  full_name='GetRecordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='GetRecordsResponse.records', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=269,
)


_SUBSCRIBEONRECORDREQUEST = _descriptor.Descriptor(
  name='SubscribeOnRecordRequest',
  full_name='SubscribeOnRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SubscribeOnRecordRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=309,
)


_REMOVERECORDREQUEST = _descriptor.Descriptor(
  name='RemoveRecordRequest',
  full_name='RemoveRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RemoveRecordRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=344,
)


_ACTIONREPORT = _descriptor.Descriptor(
  name='ActionReport',
  full_name='ActionReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccessful', full_name='ActionReport.isSuccessful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ActionReport.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_message', full_name='ActionReport._message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=346,
  serialized_end=416,
)

_GETCAMERASRESULT.fields_by_name['list'].message_type = _CAMERA
_ACTIONREPORT.oneofs_by_name['_message'].fields.append(
  _ACTIONREPORT.fields_by_name['message'])
_ACTIONREPORT.fields_by_name['message'].containing_oneof = _ACTIONREPORT.oneofs_by_name['_message']
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['Camera'] = _CAMERA
DESCRIPTOR.message_types_by_name['GetCamerasResult'] = _GETCAMERASRESULT
DESCRIPTOR.message_types_by_name['SetCameraActivenessRequest'] = _SETCAMERAACTIVENESSREQUEST
DESCRIPTOR.message_types_by_name['SubscribeOnCameraRequest'] = _SUBSCRIBEONCAMERAREQUEST
DESCRIPTOR.message_types_by_name['VideoChunk'] = _VIDEOCHUNK
DESCRIPTOR.message_types_by_name['GetRecordsResponse'] = _GETRECORDSRESPONSE
DESCRIPTOR.message_types_by_name['SubscribeOnRecordRequest'] = _SUBSCRIBEONRECORDREQUEST
DESCRIPTOR.message_types_by_name['RemoveRecordRequest'] = _REMOVERECORDREQUEST
DESCRIPTOR.message_types_by_name['ActionReport'] = _ACTIONREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  })
_sym_db.RegisterMessage(Void)

Camera = _reflection.GeneratedProtocolMessageType('Camera', (_message.Message,), {
  'DESCRIPTOR' : _CAMERA,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:Camera)
  })
_sym_db.RegisterMessage(Camera)

GetCamerasResult = _reflection.GeneratedProtocolMessageType('GetCamerasResult', (_message.Message,), {
  'DESCRIPTOR' : _GETCAMERASRESULT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:GetCamerasResult)
  })
_sym_db.RegisterMessage(GetCamerasResult)

SetCameraActivenessRequest = _reflection.GeneratedProtocolMessageType('SetCameraActivenessRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETCAMERAACTIVENESSREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:SetCameraActivenessRequest)
  })
_sym_db.RegisterMessage(SetCameraActivenessRequest)

SubscribeOnCameraRequest = _reflection.GeneratedProtocolMessageType('SubscribeOnCameraRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEONCAMERAREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeOnCameraRequest)
  })
_sym_db.RegisterMessage(SubscribeOnCameraRequest)

VideoChunk = _reflection.GeneratedProtocolMessageType('VideoChunk', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOCHUNK,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:VideoChunk)
  })
_sym_db.RegisterMessage(VideoChunk)

GetRecordsResponse = _reflection.GeneratedProtocolMessageType('GetRecordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRECORDSRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:GetRecordsResponse)
  })
_sym_db.RegisterMessage(GetRecordsResponse)

SubscribeOnRecordRequest = _reflection.GeneratedProtocolMessageType('SubscribeOnRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEONRECORDREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeOnRecordRequest)
  })
_sym_db.RegisterMessage(SubscribeOnRecordRequest)

RemoveRecordRequest = _reflection.GeneratedProtocolMessageType('RemoveRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVERECORDREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:RemoveRecordRequest)
  })
_sym_db.RegisterMessage(RemoveRecordRequest)

ActionReport = _reflection.GeneratedProtocolMessageType('ActionReport', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREPORT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ActionReport)
  })
_sym_db.RegisterMessage(ActionReport)



_API = _descriptor.ServiceDescriptor(
  name='API',
  full_name='API',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=419,
  serialized_end=764,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCameras',
    full_name='API.GetCameras',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_GETCAMERASRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetCameraActiveness',
    full_name='API.SetCameraActiveness',
    index=1,
    containing_service=None,
    input_type=_SETCAMERAACTIVENESSREQUEST,
    output_type=_ACTIONREPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeOnCamera',
    full_name='API.SubscribeOnCamera',
    index=2,
    containing_service=None,
    input_type=_SUBSCRIBEONCAMERAREQUEST,
    output_type=_VIDEOCHUNK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRecords',
    full_name='API.GetRecords',
    index=3,
    containing_service=None,
    input_type=_VOID,
    output_type=_GETRECORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeOnRecord',
    full_name='API.SubscribeOnRecord',
    index=4,
    containing_service=None,
    input_type=_SUBSCRIBEONRECORDREQUEST,
    output_type=_VIDEOCHUNK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveRecord',
    full_name='API.RemoveRecord',
    index=5,
    containing_service=None,
    input_type=_REMOVERECORDREQUEST,
    output_type=_ACTIONREPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['API'] = _API

# @@protoc_insertion_point(module_scope)
